### ISSUE TITLE
read_html encoding issue (Windows 1252 locale)

### ISSUE THREAD

**Issue by thomasd2** [hadley/rvest#118] opened 2015-11-03 16:45 UTC
If I safe the following minimal html code with UTF-8 encoding in a text editor:
 `<!doctype html>
  <meta charset=utf-8>
 <title>blah</title>
 <p class="normalclass"> I'm the content</p>
 <p class="umlautclassöäü"> I'm the content</p>
 <p class="withspace&nbsp;1"> I'm the content</p>`

This is what happens when I read it with rvest version  0.3.0 under R 3.2.2 with RStudio 0.98 (the locale on my Windows 7 machine is windows-1252):
`h <- read_html("tmpminimalutf8.html")`
`h` (...the umlaut characters are not correctly shown on screen)
`sel1 <- html_nodes(h, xpath = "body/*")`
`(classes <- html_attr(sel1,"class")) # classes shown correctly on screen`
[1] "normalclass"    "umlautclassöäü" "withspace 1" 
`sel2 <- html_nodes(h, xpath = "body/*[@class='umlautclassöäü']") `
`sel2 # empty`
{xml_nodeset (0)}
`classes[3]`
[1] "withspace 1"
`classes[3] == "withspace 1"` 
[1] FALSE
I also tried to read the html file first using read_file from readr (with default options). The result of this first step displays correctly on screen, but when I continue as above I get the same issues. A colleague replicated the issue on another Windows machine. On a Mac with an UTF locale, the Umlaut issue didn't show up, but the test in the last line above also returned a False.

Any hints are appreciated - and thanks for all the great packages!

**Comment by hadley** [comment] 2015-12-12 16:46
I think this is due to bugs in xml2 which have either been fixed or will be fixed for the next version. If you can make a reproducible example using xml2, please file a bug at https://github.com/hadley/xml2/issues

**Closed by hadley** 2015-12-12 16:46 UTC
