### ISSUE TITLE
[Question] use rvest with json pages?

### ISSUE THREAD

**Issue by happyshows** [hadley/rvest#134] opened 2016-01-20 18:53 UTC
Hi,

I'm trying to scrap some data on a stash server on our intranet. However, the html_node() function doesn't work as the page does not seem to be in html. Not an issue in chrome though.
Error: Current page doesn't appear to be html.

Then I ran httr::headers(html_session(url)) and got the following info:
$server
[1] "Apache-Coyote/1.1"

$`x-arequestid`
[1] "@19C0U7Dx763x8310199x0"

$`x-asen`
[1] "SEN-3695001"

$`cache-control`
[1] "no-cache, no-transform"

$vary
[1] "X-AUSERNAME,Accept-Encoding"

$`content-encoding`
[1] "gzip"

$`transfer-encoding`
[1] "chunked"

$`x-content-type-options`
[1] "nosniff"

$`content-type`
[1] "application/json;charset=UTF-8"

$date
[1] "Wed, 20 Jan 2016 18:43:50 GMT"

attr(,"class")
[1] "insensitive" "list"

I know jsonlite+GET function might get me the content, but I need to use rvest for the authentication portion.

Please advise

thanks.

**Comment by hadley** [comment] 2016-06-15 21:50
Basically duplicate of #96 - rvest currently lacks a method that allows you to extract arbitrary content

**Closed by hadley** 2016-06-15 21:50 UTC
